$cursor = rgb(9f9e99)
$cursor_text_color = rgb(101113)

$foreground = rgb(9f9e99)
$background = rgb(000000)

$selection_foreground = rgb(e1ffe5)
$selection_background = rgb(4a4253)

# Black
$color0 = rgb(101113)
$color8 = rgb(4a4253)

# Red
$color1 = rgb(93554b)
$color9 = rgb(93554b)

# Green
$color2 = rgb(51606a)
$color10 = rgb(a7d8b0)

# Yellow
$color3 = rgb(ac7f7b)
$color11 = rgb(e1ffe5)

# Blue
$color4 = rgb(697a9a)
$color12 = rgb(8288A0)

# Magenta
$color5 = rgb(83799C)
$color13 = rgb(997e95)

# Cyan
$color6 = rgb(7a837c)
$color14 = rgb(879493)

# White
$color7 = rgb(9f9e99)
$color15 = rgb(A8A7A2)
