run ~/.config/tmux/plugins/tmux-dotbar/dotbar.tmux

set -g @tmux-dotbar-bg "#000000"
set -g @tmux-dotbar-fg "#665c54"
set -g @tmux-dotbar-fg-current "#f0e4be"
set -g @tmux-dotbar-fg-session "#a69a88"
set -g @tmux-dotbar-fg-prefix "#9b6d0f"

set -g @tmux-dotbar-right true

set-option -g status-position top

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-space
bind C-space send-prefix



bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind v split-window -v -c "#{pane_current_path}"
bind s split-window -h -c "#{pane_current_path}"
